### ISSUE TITLE
Request for Code Release Timeline 

### ISSUE THREAD

**Issue by FanYang1234** [mackelab/LDNS#1]
Hi. Do you have an estimate for when the code will be released? I tried to reimplement your approach, but my latent space does not look right. I was trying to build upon your work, and for this, it would be a huge help if at least the part for the autoencoder was released. Thank you!

**Comment by jaivardhankapoor** [comment]
Hello,

Thanks for your interest in our work!
We are in process of cleaning the codebase for release. We will push the core code in 2-3 days.

Jai

**Comment by FanYang1234** [comment]
Thank you, looking forward to it!

Fan
